apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blogmaps.blogmap.io
spec:
  group: blogmap.io
  names:
    kind: Blogmap
    listKind: BlogmapList
    plural: blogmaps
    singular: blogmap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
