kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: blogmap-operator
subjects:
  - kind: ServiceAccount
    name: blogmap-operator
roleRef:
  kind: Role
  name: blogmap-operator
  apiGroup: rbac.authorization.k8s.io
